# HUIT Cloud Pattern - Application Stack

environment: dev
cloud_provider: aws
location: us-east-1

prerequisites:
- type: VpcStack
  name: VpcBaseInfo
  stack_name: DEV-VPC-EXT
- type: AccountInfraServicesStack
  name: HuitCloudDevInfra
  stack_name: account-infra-services-huitclouddev

# Common settings across all substacks
common:
  foo: bar


# List of all substacks with nested properties
substacks:
- name: helloworld-java-dev
  type: java_tomcat_ci_s3
  transfer_files:
    - target/helloworldtomcat.war
  EC2RegionImageID: ami-146e2a7c
  EC2InstanceType: t2.micro
  AutoScalingGroupMaxSize: 2
  AutoScalingGroupMinSize: 2
  LaunchConfigKeyName: magnuskey
  decorators:
    - type: ElbDnsDecorator
      name: AppDns
      apply_to_component_type: Elb
      domain: dev.cloud.huit.harvard.edu
    - type: LaunchConfigurationFileDeployerDecorator
      name: AppDeployment
      apply_to_component_type: LaunchConfiguration
      file_deploys:
        - bucket_file_name: helloworldtomcat.war
          instance_file_name: /usr/share/tomcat7/webapps/ROOT.war
    
  
